// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filter_avatar.proto

#ifndef PROTOBUF_filter_5favatar_2eproto__INCLUDED
#define PROTOBUF_filter_5favatar_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_filter_5favatar_2eproto();
void protobuf_AssignDesc_filter_5favatar_2eproto();
void protobuf_ShutdownFile_filter_5favatar_2eproto();

class BINFilterAvatarRequest;
class BINFilterAvatarResponse;

// ===================================================================

class BINFilterAvatarRequest : public ::google::protobuf::Message {
 public:
  BINFilterAvatarRequest();
  virtual ~BINFilterAvatarRequest();

  BINFilterAvatarRequest(const BINFilterAvatarRequest& from);

  inline BINFilterAvatarRequest& operator=(const BINFilterAvatarRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BINFilterAvatarRequest& default_instance();

  void Swap(BINFilterAvatarRequest* other);

  // implements Message ----------------------------------------------

  BINFilterAvatarRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BINFilterAvatarRequest& from);
  void MergeFrom(const BINFilterAvatarRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 firstResult = 1;
  inline bool has_firstresult() const;
  inline void clear_firstresult();
  static const int kFirstResultFieldNumber = 1;
  inline ::google::protobuf::int32 firstresult() const;
  inline void set_firstresult(::google::protobuf::int32 value);

  // required int32 maxResult = 2;
  inline bool has_maxresult() const;
  inline void clear_maxresult();
  static const int kMaxResultFieldNumber = 2;
  inline ::google::protobuf::int32 maxresult() const;
  inline void set_maxresult(::google::protobuf::int32 value);

  // optional int32 type = 3;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:BINFilterAvatarRequest)
 private:
  inline void set_has_firstresult();
  inline void clear_has_firstresult();
  inline void set_has_maxresult();
  inline void clear_has_maxresult();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 firstresult_;
  ::google::protobuf::int32 maxresult_;
  ::google::protobuf::int32 type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_filter_5favatar_2eproto();
  friend void protobuf_AssignDesc_filter_5favatar_2eproto();
  friend void protobuf_ShutdownFile_filter_5favatar_2eproto();

  void InitAsDefaultInstance();
  static BINFilterAvatarRequest* default_instance_;
};
// -------------------------------------------------------------------

class BINFilterAvatarResponse : public ::google::protobuf::Message {
 public:
  BINFilterAvatarResponse();
  virtual ~BINFilterAvatarResponse();

  BINFilterAvatarResponse(const BINFilterAvatarResponse& from);

  inline BINFilterAvatarResponse& operator=(const BINFilterAvatarResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BINFilterAvatarResponse& default_instance();

  void Swap(BINFilterAvatarResponse* other);

  // implements Message ----------------------------------------------

  BINFilterAvatarResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BINFilterAvatarResponse& from);
  void MergeFrom(const BINFilterAvatarResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool responseCode = 1;
  inline bool has_responsecode() const;
  inline void clear_responsecode();
  static const int kResponseCodeFieldNumber = 1;
  inline bool responsecode() const;
  inline void set_responsecode(bool value);

  // optional string message = 2;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 2;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // repeated int32 avatarIds = 3;
  inline int avatarids_size() const;
  inline void clear_avatarids();
  static const int kAvatarIdsFieldNumber = 3;
  inline ::google::protobuf::int32 avatarids(int index) const;
  inline void set_avatarids(int index, ::google::protobuf::int32 value);
  inline void add_avatarids(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      avatarids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_avatarids();

  // optional int32 inUseAvatarId = 4;
  inline bool has_inuseavatarid() const;
  inline void clear_inuseavatarid();
  static const int kInUseAvatarIdFieldNumber = 4;
  inline ::google::protobuf::int32 inuseavatarid() const;
  inline void set_inuseavatarid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:BINFilterAvatarResponse)
 private:
  inline void set_has_responsecode();
  inline void clear_has_responsecode();
  inline void set_has_message();
  inline void clear_has_message();
  inline void set_has_inuseavatarid();
  inline void clear_has_inuseavatarid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* message_;
  bool responsecode_;
  ::google::protobuf::int32 inuseavatarid_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > avatarids_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_filter_5favatar_2eproto();
  friend void protobuf_AssignDesc_filter_5favatar_2eproto();
  friend void protobuf_ShutdownFile_filter_5favatar_2eproto();

  void InitAsDefaultInstance();
  static BINFilterAvatarResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// BINFilterAvatarRequest

// required int32 firstResult = 1;
inline bool BINFilterAvatarRequest::has_firstresult() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BINFilterAvatarRequest::set_has_firstresult() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BINFilterAvatarRequest::clear_has_firstresult() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BINFilterAvatarRequest::clear_firstresult() {
  firstresult_ = 0;
  clear_has_firstresult();
}
inline ::google::protobuf::int32 BINFilterAvatarRequest::firstresult() const {
  return firstresult_;
}
inline void BINFilterAvatarRequest::set_firstresult(::google::protobuf::int32 value) {
  set_has_firstresult();
  firstresult_ = value;
}

// required int32 maxResult = 2;
inline bool BINFilterAvatarRequest::has_maxresult() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BINFilterAvatarRequest::set_has_maxresult() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BINFilterAvatarRequest::clear_has_maxresult() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BINFilterAvatarRequest::clear_maxresult() {
  maxresult_ = 0;
  clear_has_maxresult();
}
inline ::google::protobuf::int32 BINFilterAvatarRequest::maxresult() const {
  return maxresult_;
}
inline void BINFilterAvatarRequest::set_maxresult(::google::protobuf::int32 value) {
  set_has_maxresult();
  maxresult_ = value;
}

// optional int32 type = 3;
inline bool BINFilterAvatarRequest::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BINFilterAvatarRequest::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BINFilterAvatarRequest::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BINFilterAvatarRequest::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 BINFilterAvatarRequest::type() const {
  return type_;
}
inline void BINFilterAvatarRequest::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}

// -------------------------------------------------------------------

// BINFilterAvatarResponse

// required bool responseCode = 1;
inline bool BINFilterAvatarResponse::has_responsecode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BINFilterAvatarResponse::set_has_responsecode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BINFilterAvatarResponse::clear_has_responsecode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BINFilterAvatarResponse::clear_responsecode() {
  responsecode_ = false;
  clear_has_responsecode();
}
inline bool BINFilterAvatarResponse::responsecode() const {
  return responsecode_;
}
inline void BINFilterAvatarResponse::set_responsecode(bool value) {
  set_has_responsecode();
  responsecode_ = value;
}

// optional string message = 2;
inline bool BINFilterAvatarResponse::has_message() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BINFilterAvatarResponse::set_has_message() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BINFilterAvatarResponse::clear_has_message() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BINFilterAvatarResponse::clear_message() {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& BINFilterAvatarResponse::message() const {
  return *message_;
}
inline void BINFilterAvatarResponse::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void BINFilterAvatarResponse::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void BINFilterAvatarResponse::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINFilterAvatarResponse::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  return message_;
}
inline ::std::string* BINFilterAvatarResponse::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINFilterAvatarResponse::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated int32 avatarIds = 3;
inline int BINFilterAvatarResponse::avatarids_size() const {
  return avatarids_.size();
}
inline void BINFilterAvatarResponse::clear_avatarids() {
  avatarids_.Clear();
}
inline ::google::protobuf::int32 BINFilterAvatarResponse::avatarids(int index) const {
  return avatarids_.Get(index);
}
inline void BINFilterAvatarResponse::set_avatarids(int index, ::google::protobuf::int32 value) {
  avatarids_.Set(index, value);
}
inline void BINFilterAvatarResponse::add_avatarids(::google::protobuf::int32 value) {
  avatarids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
BINFilterAvatarResponse::avatarids() const {
  return avatarids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
BINFilterAvatarResponse::mutable_avatarids() {
  return &avatarids_;
}

// optional int32 inUseAvatarId = 4;
inline bool BINFilterAvatarResponse::has_inuseavatarid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BINFilterAvatarResponse::set_has_inuseavatarid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BINFilterAvatarResponse::clear_has_inuseavatarid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BINFilterAvatarResponse::clear_inuseavatarid() {
  inuseavatarid_ = 0;
  clear_has_inuseavatarid();
}
inline ::google::protobuf::int32 BINFilterAvatarResponse::inuseavatarid() const {
  return inuseavatarid_;
}
inline void BINFilterAvatarResponse::set_inuseavatarid(::google::protobuf::int32 value) {
  set_has_inuseavatarid();
  inuseavatarid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_filter_5favatar_2eproto__INCLUDED
