// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

#ifndef PROTOBUF_login_2eproto__INCLUDED
#define PROTOBUF_login_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "user_info.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_login_2eproto();
void protobuf_AssignDesc_login_2eproto();
void protobuf_ShutdownFile_login_2eproto();

class BINLoginRequest;
class BINLoginResponse;

// ===================================================================

class BINLoginRequest : public ::google::protobuf::Message {
 public:
  BINLoginRequest();
  virtual ~BINLoginRequest();

  BINLoginRequest(const BINLoginRequest& from);

  inline BINLoginRequest& operator=(const BINLoginRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BINLoginRequest& default_instance();

  void Swap(BINLoginRequest* other);

  // implements Message ----------------------------------------------

  BINLoginRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BINLoginRequest& from);
  void MergeFrom(const BINLoginRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string userName = 1;
  inline bool has_username() const;
  inline void clear_username();
  static const int kUserNameFieldNumber = 1;
  inline const ::std::string& username() const;
  inline void set_username(const ::std::string& value);
  inline void set_username(const char* value);
  inline void set_username(const char* value, size_t size);
  inline ::std::string* mutable_username();
  inline ::std::string* release_username();
  inline void set_allocated_username(::std::string* username);

  // required string password = 2;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 2;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // @@protoc_insertion_point(class_scope:BINLoginRequest)
 private:
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_password();
  inline void clear_has_password();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* username_;
  ::std::string* password_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static BINLoginRequest* default_instance_;
};
// -------------------------------------------------------------------

class BINLoginResponse : public ::google::protobuf::Message {
 public:
  BINLoginResponse();
  virtual ~BINLoginResponse();

  BINLoginResponse(const BINLoginResponse& from);

  inline BINLoginResponse& operator=(const BINLoginResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BINLoginResponse& default_instance();

  void Swap(BINLoginResponse* other);

  // implements Message ----------------------------------------------

  BINLoginResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BINLoginResponse& from);
  void MergeFrom(const BINLoginResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool responseCode = 1;
  inline bool has_responsecode() const;
  inline void clear_responsecode();
  static const int kResponseCodeFieldNumber = 1;
  inline bool responsecode() const;
  inline void set_responsecode(bool value);

  // optional string message = 2;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 2;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // optional .BINUserInfo userInfo = 3;
  inline bool has_userinfo() const;
  inline void clear_userinfo();
  static const int kUserInfoFieldNumber = 3;
  inline const ::BINUserInfo& userinfo() const;
  inline ::BINUserInfo* mutable_userinfo();
  inline ::BINUserInfo* release_userinfo();
  inline void set_allocated_userinfo(::BINUserInfo* userinfo);

  // optional .BINUserSetting userSetting = 4;
  inline bool has_usersetting() const;
  inline void clear_usersetting();
  static const int kUserSettingFieldNumber = 4;
  inline const ::BINUserSetting& usersetting() const;
  inline ::BINUserSetting* mutable_usersetting();
  inline ::BINUserSetting* release_usersetting();
  inline void set_allocated_usersetting(::BINUserSetting* usersetting);

  // optional string sessionId = 5;
  inline bool has_sessionid() const;
  inline void clear_sessionid();
  static const int kSessionIdFieldNumber = 5;
  inline const ::std::string& sessionid() const;
  inline void set_sessionid(const ::std::string& value);
  inline void set_sessionid(const char* value);
  inline void set_sessionid(const char* value, size_t size);
  inline ::std::string* mutable_sessionid();
  inline ::std::string* release_sessionid();
  inline void set_allocated_sessionid(::std::string* sessionid);

  // optional bool hasPlayingMatch = 6;
  inline bool has_hasplayingmatch() const;
  inline void clear_hasplayingmatch();
  static const int kHasPlayingMatchFieldNumber = 6;
  inline bool hasplayingmatch() const;
  inline void set_hasplayingmatch(bool value);

  // optional bool enableDebugLag = 7;
  inline bool has_enabledebuglag() const;
  inline void clear_enabledebuglag();
  static const int kEnableDebugLagFieldNumber = 7;
  inline bool enabledebuglag() const;
  inline void set_enabledebuglag(bool value);

  // @@protoc_insertion_point(class_scope:BINLoginResponse)
 private:
  inline void set_has_responsecode();
  inline void clear_has_responsecode();
  inline void set_has_message();
  inline void clear_has_message();
  inline void set_has_userinfo();
  inline void clear_has_userinfo();
  inline void set_has_usersetting();
  inline void clear_has_usersetting();
  inline void set_has_sessionid();
  inline void clear_has_sessionid();
  inline void set_has_hasplayingmatch();
  inline void clear_has_hasplayingmatch();
  inline void set_has_enabledebuglag();
  inline void clear_has_enabledebuglag();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* message_;
  ::BINUserInfo* userinfo_;
  ::BINUserSetting* usersetting_;
  ::std::string* sessionid_;
  bool responsecode_;
  bool hasplayingmatch_;
  bool enabledebuglag_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static BINLoginResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// BINLoginRequest

// required string userName = 1;
inline bool BINLoginRequest::has_username() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BINLoginRequest::set_has_username() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BINLoginRequest::clear_has_username() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BINLoginRequest::clear_username() {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    username_->clear();
  }
  clear_has_username();
}
inline const ::std::string& BINLoginRequest::username() const {
  return *username_;
}
inline void BINLoginRequest::set_username(const ::std::string& value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(value);
}
inline void BINLoginRequest::set_username(const char* value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(value);
}
inline void BINLoginRequest::set_username(const char* value, size_t size) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINLoginRequest::mutable_username() {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  return username_;
}
inline ::std::string* BINLoginRequest::release_username() {
  clear_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = username_;
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINLoginRequest::set_allocated_username(::std::string* username) {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    delete username_;
  }
  if (username) {
    set_has_username();
    username_ = username;
  } else {
    clear_has_username();
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string password = 2;
inline bool BINLoginRequest::has_password() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BINLoginRequest::set_has_password() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BINLoginRequest::clear_has_password() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BINLoginRequest::clear_password() {
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    password_->clear();
  }
  clear_has_password();
}
inline const ::std::string& BINLoginRequest::password() const {
  return *password_;
}
inline void BINLoginRequest::set_password(const ::std::string& value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(value);
}
inline void BINLoginRequest::set_password(const char* value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(value);
}
inline void BINLoginRequest::set_password(const char* value, size_t size) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINLoginRequest::mutable_password() {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  return password_;
}
inline ::std::string* BINLoginRequest::release_password() {
  clear_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = password_;
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINLoginRequest::set_allocated_password(::std::string* password) {
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    delete password_;
  }
  if (password) {
    set_has_password();
    password_ = password;
  } else {
    clear_has_password();
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// BINLoginResponse

// required bool responseCode = 1;
inline bool BINLoginResponse::has_responsecode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BINLoginResponse::set_has_responsecode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BINLoginResponse::clear_has_responsecode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BINLoginResponse::clear_responsecode() {
  responsecode_ = false;
  clear_has_responsecode();
}
inline bool BINLoginResponse::responsecode() const {
  return responsecode_;
}
inline void BINLoginResponse::set_responsecode(bool value) {
  set_has_responsecode();
  responsecode_ = value;
}

// optional string message = 2;
inline bool BINLoginResponse::has_message() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BINLoginResponse::set_has_message() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BINLoginResponse::clear_has_message() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BINLoginResponse::clear_message() {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& BINLoginResponse::message() const {
  return *message_;
}
inline void BINLoginResponse::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void BINLoginResponse::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void BINLoginResponse::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINLoginResponse::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  return message_;
}
inline ::std::string* BINLoginResponse::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINLoginResponse::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .BINUserInfo userInfo = 3;
inline bool BINLoginResponse::has_userinfo() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BINLoginResponse::set_has_userinfo() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BINLoginResponse::clear_has_userinfo() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BINLoginResponse::clear_userinfo() {
  if (userinfo_ != NULL) userinfo_->::BINUserInfo::Clear();
  clear_has_userinfo();
}
inline const ::BINUserInfo& BINLoginResponse::userinfo() const {
  return userinfo_ != NULL ? *userinfo_ : *default_instance_->userinfo_;
}
inline ::BINUserInfo* BINLoginResponse::mutable_userinfo() {
  set_has_userinfo();
  if (userinfo_ == NULL) userinfo_ = new ::BINUserInfo;
  return userinfo_;
}
inline ::BINUserInfo* BINLoginResponse::release_userinfo() {
  clear_has_userinfo();
  ::BINUserInfo* temp = userinfo_;
  userinfo_ = NULL;
  return temp;
}
inline void BINLoginResponse::set_allocated_userinfo(::BINUserInfo* userinfo) {
  delete userinfo_;
  userinfo_ = userinfo;
  if (userinfo) {
    set_has_userinfo();
  } else {
    clear_has_userinfo();
  }
}

// optional .BINUserSetting userSetting = 4;
inline bool BINLoginResponse::has_usersetting() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BINLoginResponse::set_has_usersetting() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BINLoginResponse::clear_has_usersetting() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BINLoginResponse::clear_usersetting() {
  if (usersetting_ != NULL) usersetting_->::BINUserSetting::Clear();
  clear_has_usersetting();
}
inline const ::BINUserSetting& BINLoginResponse::usersetting() const {
  return usersetting_ != NULL ? *usersetting_ : *default_instance_->usersetting_;
}
inline ::BINUserSetting* BINLoginResponse::mutable_usersetting() {
  set_has_usersetting();
  if (usersetting_ == NULL) usersetting_ = new ::BINUserSetting;
  return usersetting_;
}
inline ::BINUserSetting* BINLoginResponse::release_usersetting() {
  clear_has_usersetting();
  ::BINUserSetting* temp = usersetting_;
  usersetting_ = NULL;
  return temp;
}
inline void BINLoginResponse::set_allocated_usersetting(::BINUserSetting* usersetting) {
  delete usersetting_;
  usersetting_ = usersetting;
  if (usersetting) {
    set_has_usersetting();
  } else {
    clear_has_usersetting();
  }
}

// optional string sessionId = 5;
inline bool BINLoginResponse::has_sessionid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void BINLoginResponse::set_has_sessionid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void BINLoginResponse::clear_has_sessionid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void BINLoginResponse::clear_sessionid() {
  if (sessionid_ != &::google::protobuf::internal::kEmptyString) {
    sessionid_->clear();
  }
  clear_has_sessionid();
}
inline const ::std::string& BINLoginResponse::sessionid() const {
  return *sessionid_;
}
inline void BINLoginResponse::set_sessionid(const ::std::string& value) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(value);
}
inline void BINLoginResponse::set_sessionid(const char* value) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(value);
}
inline void BINLoginResponse::set_sessionid(const char* value, size_t size) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINLoginResponse::mutable_sessionid() {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  return sessionid_;
}
inline ::std::string* BINLoginResponse::release_sessionid() {
  clear_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = sessionid_;
    sessionid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINLoginResponse::set_allocated_sessionid(::std::string* sessionid) {
  if (sessionid_ != &::google::protobuf::internal::kEmptyString) {
    delete sessionid_;
  }
  if (sessionid) {
    set_has_sessionid();
    sessionid_ = sessionid;
  } else {
    clear_has_sessionid();
    sessionid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bool hasPlayingMatch = 6;
inline bool BINLoginResponse::has_hasplayingmatch() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void BINLoginResponse::set_has_hasplayingmatch() {
  _has_bits_[0] |= 0x00000020u;
}
inline void BINLoginResponse::clear_has_hasplayingmatch() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void BINLoginResponse::clear_hasplayingmatch() {
  hasplayingmatch_ = false;
  clear_has_hasplayingmatch();
}
inline bool BINLoginResponse::hasplayingmatch() const {
  return hasplayingmatch_;
}
inline void BINLoginResponse::set_hasplayingmatch(bool value) {
  set_has_hasplayingmatch();
  hasplayingmatch_ = value;
}

// optional bool enableDebugLag = 7;
inline bool BINLoginResponse::has_enabledebuglag() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void BINLoginResponse::set_has_enabledebuglag() {
  _has_bits_[0] |= 0x00000040u;
}
inline void BINLoginResponse::clear_has_enabledebuglag() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void BINLoginResponse::clear_enabledebuglag() {
  enabledebuglag_ = false;
  clear_has_enabledebuglag();
}
inline bool BINLoginResponse::enabledebuglag() const {
  return enabledebuglag_;
}
inline void BINLoginResponse::set_enabledebuglag(bool value) {
  set_has_enabledebuglag();
  enabledebuglag_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_login_2eproto__INCLUDED
