// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: turn.proto

#ifndef PROTOBUF_turn_2eproto__INCLUDED
#define PROTOBUF_turn_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "map_field_entry.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_turn_2eproto();
void protobuf_AssignDesc_turn_2eproto();
void protobuf_ShutdownFile_turn_2eproto();

class BINTurnRequest;
class BINTurnResponse;

// ===================================================================

class BINTurnRequest : public ::google::protobuf::Message {
 public:
  BINTurnRequest();
  virtual ~BINTurnRequest();

  BINTurnRequest(const BINTurnRequest& from);

  inline BINTurnRequest& operator=(const BINTurnRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BINTurnRequest& default_instance();

  void Swap(BINTurnRequest* other);

  // implements Message ----------------------------------------------

  BINTurnRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BINTurnRequest& from);
  void MergeFrom(const BINTurnRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 roomIndex = 1;
  inline bool has_roomindex() const;
  inline void clear_roomindex();
  static const int kRoomIndexFieldNumber = 1;
  inline ::google::protobuf::int32 roomindex() const;
  inline void set_roomindex(::google::protobuf::int32 value);

  // repeated .BINMapFieldEntry args = 2;
  inline int args_size() const;
  inline void clear_args();
  static const int kArgsFieldNumber = 2;
  inline const ::BINMapFieldEntry& args(int index) const;
  inline ::BINMapFieldEntry* mutable_args(int index);
  inline ::BINMapFieldEntry* add_args();
  inline const ::google::protobuf::RepeatedPtrField< ::BINMapFieldEntry >&
      args() const;
  inline ::google::protobuf::RepeatedPtrField< ::BINMapFieldEntry >*
      mutable_args();

  // @@protoc_insertion_point(class_scope:BINTurnRequest)
 private:
  inline void set_has_roomindex();
  inline void clear_has_roomindex();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::BINMapFieldEntry > args_;
  ::google::protobuf::int32 roomindex_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_turn_2eproto();
  friend void protobuf_AssignDesc_turn_2eproto();
  friend void protobuf_ShutdownFile_turn_2eproto();

  void InitAsDefaultInstance();
  static BINTurnRequest* default_instance_;
};
// -------------------------------------------------------------------

class BINTurnResponse : public ::google::protobuf::Message {
 public:
  BINTurnResponse();
  virtual ~BINTurnResponse();

  BINTurnResponse(const BINTurnResponse& from);

  inline BINTurnResponse& operator=(const BINTurnResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BINTurnResponse& default_instance();

  void Swap(BINTurnResponse* other);

  // implements Message ----------------------------------------------

  BINTurnResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BINTurnResponse& from);
  void MergeFrom(const BINTurnResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool responseCode = 1;
  inline bool has_responsecode() const;
  inline void clear_responsecode();
  static const int kResponseCodeFieldNumber = 1;
  inline bool responsecode() const;
  inline void set_responsecode(bool value);

  // optional string message = 2;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 2;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // optional int64 currentTurnUserId = 3;
  inline bool has_currentturnuserid() const;
  inline void clear_currentturnuserid();
  static const int kCurrentTurnUserIdFieldNumber = 3;
  inline ::google::protobuf::int64 currentturnuserid() const;
  inline void set_currentturnuserid(::google::protobuf::int64 value);

  // optional int64 nextTurnUserId = 4;
  inline bool has_nextturnuserid() const;
  inline void clear_nextturnuserid();
  static const int kNextTurnUserIdFieldNumber = 4;
  inline ::google::protobuf::int64 nextturnuserid() const;
  inline void set_nextturnuserid(::google::protobuf::int64 value);

  // optional bool matchEnd = 5;
  inline bool has_matchend() const;
  inline void clear_matchend();
  static const int kMatchEndFieldNumber = 5;
  inline bool matchend() const;
  inline void set_matchend(bool value);

  // optional int32 countDownTimer = 6;
  inline bool has_countdowntimer() const;
  inline void clear_countdowntimer();
  static const int kCountDownTimerFieldNumber = 6;
  inline ::google::protobuf::int32 countdowntimer() const;
  inline void set_countdowntimer(::google::protobuf::int32 value);

  // repeated .BINMapFieldEntry args = 7;
  inline int args_size() const;
  inline void clear_args();
  static const int kArgsFieldNumber = 7;
  inline const ::BINMapFieldEntry& args(int index) const;
  inline ::BINMapFieldEntry* mutable_args(int index);
  inline ::BINMapFieldEntry* add_args();
  inline const ::google::protobuf::RepeatedPtrField< ::BINMapFieldEntry >&
      args() const;
  inline ::google::protobuf::RepeatedPtrField< ::BINMapFieldEntry >*
      mutable_args();

  // @@protoc_insertion_point(class_scope:BINTurnResponse)
 private:
  inline void set_has_responsecode();
  inline void clear_has_responsecode();
  inline void set_has_message();
  inline void clear_has_message();
  inline void set_has_currentturnuserid();
  inline void clear_has_currentturnuserid();
  inline void set_has_nextturnuserid();
  inline void clear_has_nextturnuserid();
  inline void set_has_matchend();
  inline void clear_has_matchend();
  inline void set_has_countdowntimer();
  inline void clear_has_countdowntimer();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* message_;
  ::google::protobuf::int64 currentturnuserid_;
  ::google::protobuf::int64 nextturnuserid_;
  bool responsecode_;
  bool matchend_;
  ::google::protobuf::int32 countdowntimer_;
  ::google::protobuf::RepeatedPtrField< ::BINMapFieldEntry > args_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_turn_2eproto();
  friend void protobuf_AssignDesc_turn_2eproto();
  friend void protobuf_ShutdownFile_turn_2eproto();

  void InitAsDefaultInstance();
  static BINTurnResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// BINTurnRequest

// required int32 roomIndex = 1;
inline bool BINTurnRequest::has_roomindex() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BINTurnRequest::set_has_roomindex() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BINTurnRequest::clear_has_roomindex() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BINTurnRequest::clear_roomindex() {
  roomindex_ = 0;
  clear_has_roomindex();
}
inline ::google::protobuf::int32 BINTurnRequest::roomindex() const {
  return roomindex_;
}
inline void BINTurnRequest::set_roomindex(::google::protobuf::int32 value) {
  set_has_roomindex();
  roomindex_ = value;
}

// repeated .BINMapFieldEntry args = 2;
inline int BINTurnRequest::args_size() const {
  return args_.size();
}
inline void BINTurnRequest::clear_args() {
  args_.Clear();
}
inline const ::BINMapFieldEntry& BINTurnRequest::args(int index) const {
  return args_.Get(index);
}
inline ::BINMapFieldEntry* BINTurnRequest::mutable_args(int index) {
  return args_.Mutable(index);
}
inline ::BINMapFieldEntry* BINTurnRequest::add_args() {
  return args_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::BINMapFieldEntry >&
BINTurnRequest::args() const {
  return args_;
}
inline ::google::protobuf::RepeatedPtrField< ::BINMapFieldEntry >*
BINTurnRequest::mutable_args() {
  return &args_;
}

// -------------------------------------------------------------------

// BINTurnResponse

// required bool responseCode = 1;
inline bool BINTurnResponse::has_responsecode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BINTurnResponse::set_has_responsecode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BINTurnResponse::clear_has_responsecode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BINTurnResponse::clear_responsecode() {
  responsecode_ = false;
  clear_has_responsecode();
}
inline bool BINTurnResponse::responsecode() const {
  return responsecode_;
}
inline void BINTurnResponse::set_responsecode(bool value) {
  set_has_responsecode();
  responsecode_ = value;
}

// optional string message = 2;
inline bool BINTurnResponse::has_message() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BINTurnResponse::set_has_message() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BINTurnResponse::clear_has_message() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BINTurnResponse::clear_message() {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& BINTurnResponse::message() const {
  return *message_;
}
inline void BINTurnResponse::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void BINTurnResponse::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void BINTurnResponse::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINTurnResponse::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  return message_;
}
inline ::std::string* BINTurnResponse::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINTurnResponse::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int64 currentTurnUserId = 3;
inline bool BINTurnResponse::has_currentturnuserid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BINTurnResponse::set_has_currentturnuserid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BINTurnResponse::clear_has_currentturnuserid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BINTurnResponse::clear_currentturnuserid() {
  currentturnuserid_ = GOOGLE_LONGLONG(0);
  clear_has_currentturnuserid();
}
inline ::google::protobuf::int64 BINTurnResponse::currentturnuserid() const {
  return currentturnuserid_;
}
inline void BINTurnResponse::set_currentturnuserid(::google::protobuf::int64 value) {
  set_has_currentturnuserid();
  currentturnuserid_ = value;
}

// optional int64 nextTurnUserId = 4;
inline bool BINTurnResponse::has_nextturnuserid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BINTurnResponse::set_has_nextturnuserid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BINTurnResponse::clear_has_nextturnuserid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BINTurnResponse::clear_nextturnuserid() {
  nextturnuserid_ = GOOGLE_LONGLONG(0);
  clear_has_nextturnuserid();
}
inline ::google::protobuf::int64 BINTurnResponse::nextturnuserid() const {
  return nextturnuserid_;
}
inline void BINTurnResponse::set_nextturnuserid(::google::protobuf::int64 value) {
  set_has_nextturnuserid();
  nextturnuserid_ = value;
}

// optional bool matchEnd = 5;
inline bool BINTurnResponse::has_matchend() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void BINTurnResponse::set_has_matchend() {
  _has_bits_[0] |= 0x00000010u;
}
inline void BINTurnResponse::clear_has_matchend() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void BINTurnResponse::clear_matchend() {
  matchend_ = false;
  clear_has_matchend();
}
inline bool BINTurnResponse::matchend() const {
  return matchend_;
}
inline void BINTurnResponse::set_matchend(bool value) {
  set_has_matchend();
  matchend_ = value;
}

// optional int32 countDownTimer = 6;
inline bool BINTurnResponse::has_countdowntimer() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void BINTurnResponse::set_has_countdowntimer() {
  _has_bits_[0] |= 0x00000020u;
}
inline void BINTurnResponse::clear_has_countdowntimer() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void BINTurnResponse::clear_countdowntimer() {
  countdowntimer_ = 0;
  clear_has_countdowntimer();
}
inline ::google::protobuf::int32 BINTurnResponse::countdowntimer() const {
  return countdowntimer_;
}
inline void BINTurnResponse::set_countdowntimer(::google::protobuf::int32 value) {
  set_has_countdowntimer();
  countdowntimer_ = value;
}

// repeated .BINMapFieldEntry args = 7;
inline int BINTurnResponse::args_size() const {
  return args_.size();
}
inline void BINTurnResponse::clear_args() {
  args_.Clear();
}
inline const ::BINMapFieldEntry& BINTurnResponse::args(int index) const {
  return args_.Get(index);
}
inline ::BINMapFieldEntry* BINTurnResponse::mutable_args(int index) {
  return args_.Mutable(index);
}
inline ::BINMapFieldEntry* BINTurnResponse::add_args() {
  return args_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::BINMapFieldEntry >&
BINTurnResponse::args() const {
  return args_;
}
inline ::google::protobuf::RepeatedPtrField< ::BINMapFieldEntry >*
BINTurnResponse::mutable_args() {
  return &args_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_turn_2eproto__INCLUDED
